#ifndef  _SCANNER_H_
#define _SCANNER_H_

#if ! defined(yyFlexLexerOnce)
#include <FlexLexer.h>
#endif

#include "parser.h"
#include "location.hh"

namespace ccbhj {

class Scanner : public yyFlexLexer {
public:
    Scanner(std::istream* arg_yyin ) 
        : yyFlexLexer(arg_yyin) {} 

    virtual ~Scanner() {};

    using FlexLexer::yylex;
    // This is the main lexer func, which is generated by flex according to 
    // the macro declaration YY_DECL above.
    // bison will call this function to fetch tokens.
    virtual ccbhj::Parser::token_type yylex( ccbhj::Parser::semantic_type * const yylval,
        ccbhj::Parser::location_type *location);

};

}
#endif // _SCANNER_H